import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans, Raleway } from "next/font/google";
import "./globals.css";
import HeaderComponent from "../src/components/HeaderComponent/HeaderComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-sans"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EMCUS - Software Development for Fire & Safety",
  description: "Generated by create next app",
};

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${jakartaSans.variable}
        ${raleway.variable}
        ${geistMono.variable}
      `}
    >
      <body
        className={`
          ${jakartaSans.className}
          antialiased
        `}
      >
        <div className="2xl:max-w-7xl
          2xl:mx-auto
          2xl:px-4
          px-0">
            {children}
        </div>
      </body>
    </html>
  );
}
